FROM ubuntu:20.04
#.4
#latest
MAINTAINER witon "witon@qq.com"
RUN apt-get update
RUN apt-get install -y lsb-release
RUN apt-get install -y keyboard-configuration 
RUN apt-get install -y g++
RUN apt-get install -y cmake
RUN apt-get install -y lua5.3
RUN apt-get install -y lua5.3-dev
RUN apt-get install -y libasound2-dev
RUN apt-get install -y libgtk-3-dev
RUN apt-get install -y libfontconfig1-dev
RUN apt-get install -y libglib2.0-dev
#RUN apt-get install -y libgtk2.0-dev
RUN apt-get install -y libgtk-3-dev
RUN apt-get install -y libftgl-dev
RUN apt-get install -y libfftw3-dev
RUN apt-get install -y --fix-missing libwebkit2gtk-4.0-dev