FROM ubuntu:latest
MAINTAINER witon "witon@qq.com"
RUN apt-get update
RUN apt-get install -y g++
RUN apt-get install -y cmake
RUN apt-get install -y lua5.3
RUN apt-get install -y lua5.3-dev
RUN apt-get install -y libasound2-dev
