FROM ubuntu:latest
MAINTAINER witon "witon@qq.com"
RUN apt-get update
RUN apt-get install -y g++
RUN apt-get install -y cmake
RUN apt-get install -y make
RUN apt-get install -y lua5.3
RUN apt-get install -y lua5.3-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop-minimal
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gnome
RUN apt-get install -y iptuils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y libreadline-dev
RUN apt-get install -y libfftw3-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libgtk-3-dev libwebkit2gtk-4.0-dev 
