# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1
      - uses: leafo/gh-actions-lua@v8.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

        with:
          # The version of Lua to install, must be available on https://www.lua.org/ftp/ or http://luajit.org/download.html
          luaVersion: 5.2.2
          # Command line flags passed to make when building Lua
          luaCompileFlags: # optional
      - uses: leafo/gh-actions-luarocks@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          luarocksVersion: "3.1.3"
       # Install some package
      - name: install a module
        run: luarocks install luaunit
      - name: install a module
        run: luarocks install lua-mock        
      - name: install liblua5.2
        run: sudo apt-get install liblua5.2-dev


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: lua -v

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          echo Add other actions to build,
          echo test, and deploy your project.
          lua test/test.lua
